# Generated by Django 5.1.5 on 2025-02-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='album',
            field=models.CharField(default='2024', max_length=255),
        ),
    ]
